import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster, toast } from "sonner";
import NavbarSection from "@/Sections/MainNavbar/NavbarSection";
import FooterSection from "@/Sections/Footer/Footer";
import Banner from "@/Sections/Banner/Banner";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Plaza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner />
        <NavbarSection />
        {children}
        <ScrollToTop />
        <FooterSection />

        <Toaster
          position="top-right"
          richColors
          closeButton
          duration={2000}
          pauseWhenPageIsHidden
        />
      </body>
    </html>
  );
}
