import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Home | CodeWithNimit",
    absolute: "",
    template: "%s | CodeWithNimit",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
